# Generated by Django 4.1.2 on 2022-10-16 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartamentoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamentoAcademico', models.CharField(max_length=100)),
                ('abreviacion', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'DepartamentoAcademico',
                'verbose_name_plural': 'DepartamentosAcademicos',
                'db_table': 'departamentoAcademico',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estado',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=100)),
                ('idEstado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.estado')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': 'grupo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreInstitucion', models.CharField(max_length=100)),
                ('ruta', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Institucion',
                'verbose_name_plural': 'Instituciones',
                'db_table': 'institucion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PadreMadreTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidoPaterno', models.CharField(max_length=100)),
                ('apellidoMaterno', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'PadreMadreTutor',
                'verbose_name_plural': 'PadresMadresTutores',
                'db_table': 'padreMadreTutor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tutorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domicilio', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('correoPersonal', models.EmailField(max_length=254)),
                ('semestre', models.PositiveIntegerField()),
                ('idDepartamentoAcademico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.departamentoacademico')),
                ('idGrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.grupo')),
                ('idInstitucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.institucion')),
                ('idPadreMadreTutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.padremadretutor')),
            ],
            options={
                'verbose_name': 'Tutorado',
                'verbose_name_plural': 'Tutorados',
                'db_table': 'tutorado',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PersonalTec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domicilio', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('correoPersonal', models.EmailField(max_length=254)),
                ('edificio', models.CharField(max_length=100)),
                ('idDepartamentoAcademico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.departamentoacademico')),
                ('idInstitucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.institucion')),
            ],
            options={
                'verbose_name': 'PersonalTec',
                'verbose_name_plural': 'PersonalTecs',
                'db_table': 'personalTec',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PersonalMed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domicilio', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('correoPersonal', models.EmailField(max_length=254)),
                ('edificio', models.CharField(max_length=100)),
                ('idInstitucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.institucion')),
            ],
            options={
                'verbose_name': 'PersonalMed',
                'verbose_name_plural': 'PersonalMeds',
                'db_table': 'personalMed',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='idInstitucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.institucion'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='idPersonalTec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.personaltec'),
        ),
        migrations.AddField(
            model_name='departamentoacademico',
            name='idInstitucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.institucion'),
        ),
    ]
