# Generated by Django 4.1.2 on 2022-10-17 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tutoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorado',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fechaPublicado', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('fechaLimite', models.DateField()),
                ('idEstado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.estado')),
                ('idGrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.grupo')),
                ('idPersonalTec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.personaltec')),
            ],
            options={
                'verbose_name': 'Cuestionario',
                'verbose_name_plural': 'Cuestionarios',
                'db_table': 'cuestionario',
                'ordering': ['id'],
            },
        ),
    ]
