# Generated by Django 4.1.2 on 2022-10-17 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoria', '0002_tutorado_user_cuestionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorado',
            name='idGrupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutoria.grupo'),
        ),
        migrations.AlterField(
            model_name='tutorado',
            name='idPadreMadreTutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutoria.padremadretutor'),
        ),
    ]
