# Generated by Django 4.1.2 on 2022-10-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoria', '0003_alter_tutorado_idgrupo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='ruta',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
