# Generated by Django 4.1.2 on 2022-10-17 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoria', '0006_alter_tutorado_idgrupo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='idEstado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutoria.estado'),
        ),
    ]
