# Generated by Django 4.1.2 on 2022-10-17 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoria', '0007_alter_grupo_idestado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreOrden', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
                'db_table': 'orden',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='idEstado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutoria.estado'),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='idGrupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutoria.grupo'),
        ),
        migrations.CreateModel(
            name='ReporteSemestralInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50)),
                ('ruta', models.CharField(blank=True, max_length=300, null=True)),
                ('fechaLimite', models.DateField()),
                ('idEstado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutoria.estado')),
                ('idPersonalTec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.personaltec')),
            ],
            options={
                'verbose_name': 'ReporteSemestralInstitucional',
                'verbose_name_plural': 'ReportesSemestralesInstitucionales',
                'db_table': 'reporteSemestralInstitucional',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReporteSemestralGrupal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50)),
                ('ruta', models.CharField(blank=True, max_length=300, null=True)),
                ('fechaLimite', models.DateField()),
                ('idEstado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutoria.estado')),
                ('idGrupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutoria.grupo')),
                ('idPersonalTec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.personaltec')),
            ],
            options={
                'verbose_name': 'ReporteSemestralGrupal',
                'verbose_name_plural': 'ReportesSemestralesGrupales',
                'db_table': 'reporteSemestralGrupal',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReporteSemestralDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50)),
                ('ruta', models.CharField(blank=True, max_length=300, null=True)),
                ('fechaLimite', models.DateField()),
                ('idDepartamentoAcademico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.departamentoacademico')),
                ('idEstado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutoria.estado')),
                ('idPersonalTec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.personaltec')),
            ],
            options={
                'verbose_name': 'ReporteSemestralDepartamento',
                'verbose_name_plural': 'ReportesSemestralesDepartamentos',
                'db_table': 'reporteSemestralDepartamento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50)),
                ('ruta', models.CharField(blank=True, max_length=300, null=True)),
                ('fechaLimite', models.DateField()),
                ('idEstado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutoria.estado')),
                ('idInstitucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.institucion')),
            ],
            options={
                'verbose_name': 'PIT',
                'verbose_name_plural': 'PITs',
                'db_table': 'pit',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50)),
                ('ruta', models.CharField(blank=True, max_length=300, null=True)),
                ('estadoEdicion', models.CharField(max_length=50)),
                ('fechaLimite', models.DateField()),
                ('idDepartamentoAcademico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.departamentoacademico')),
                ('idEstado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutoria.estado')),
            ],
            options={
                'verbose_name': 'PAT',
                'verbose_name_plural': 'PATs',
                'db_table': 'pat',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('idOrden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.orden')),
            ],
            options={
                'verbose_name': 'Motivo',
                'verbose_name_plural': 'Motivos',
                'db_table': 'motivo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ConstanciaTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50)),
                ('ruta', models.CharField(blank=True, max_length=300, null=True)),
                ('idPersonalTec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.personaltec')),
            ],
            options={
                'verbose_name': 'ConstanciaTutor',
                'verbose_name_plural': 'ConstanciaTutores',
                'db_table': 'constanciaTutor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('horaInicio', models.TimeField()),
                ('horaFinal', models.TimeField()),
                ('horaCanalizacion', models.TimeField()),
                ('lugar', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300)),
                ('idEstado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutoria.estado')),
                ('idMotivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.motivo')),
                ('idOrden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.orden')),
                ('idPersonalMed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.personalmed')),
                ('idPersonalTec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.personaltec')),
                ('idTutorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.tutorado')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'cita',
                'ordering': ['id'],
            },
        ),
    ]
