# Generated by Django 4.1.2 on 2022-10-17 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoria', '0009_alter_cita_descripcion_alter_cita_horacanalizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupoRespuesta', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'GrupoRespuesta',
                'verbose_name_plural': 'GrupoRespuesta',
                'db_table': 'grupoRespuesta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=100)),
                ('idGrupoRespuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.gruporespuesta')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'db_table': 'pregunta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=100)),
                ('idGrupoRespuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.gruporespuesta')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'db_table': 'respuesta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaContestada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.cuestionario')),
                ('idPregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.pregunta')),
                ('idRespuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.respuesta')),
                ('idTutorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.tutorado')),
            ],
            options={
                'verbose_name': 'RespuestaContestada',
                'verbose_name_plural': 'RespuestasContestadas',
                'db_table': 'respuestaContestada',
                'ordering': ['id'],
            },
        ),
    ]
