# Generated by Django 4.1.2 on 2022-10-22 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoria', '0011_personalmed_user_personaltec_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionario',
            name='ruta',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='CuestionarioContestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(max_length=300)),
                ('idCuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.cuestionario')),
                ('idEstado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutoria.estado')),
                ('idTutorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.tutorado')),
            ],
            options={
                'verbose_name': 'CuestionarioContestado',
                'verbose_name_plural': 'CuestionarioContestados',
                'db_table': 'CuestionarioContestado',
                'ordering': ['id'],
            },
        ),
    ]
