# Generated by Django 4.1 on 2022-11-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoria', '0011_personalmed_user_personaltec_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.CharField(max_length=8)),
                ('nombres', models.CharField(max_length=35)),
                ('apellidos', models.CharField(max_length=35)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
