# Generated by Django 4.1 on 2022-11-11 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoria', '0012_excel2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_doc', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='Tutorado/Creditos')),
                ('comentarios', models.CharField(blank=True, max_length=200, null=True)),
                ('idEstado', models.CharField(max_length=10)),
                ('idTutorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.tutorado')),
            ],
        ),
    ]
