# Generated by Django 4.1.2 on 2022-10-23 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoria', '0013_remove_cuestionariocontestado_idestado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='padremadretutor',
            old_name='apellidoMaterno',
            new_name='apellidos',
        ),
        migrations.RemoveField(
            model_name='padremadretutor',
            name='apellidoPaterno',
        ),
    ]
