# Generated by Django 4.1.2 on 2022-10-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoria', '0014_rename_apellidomaterno_padremadretutor_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionariocontestado',
            name='archivo',
            field=models.FileField(default='a', upload_to='Respuestas/Cuestionarios/%Y/%m/%d/%H/%M/%S'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='cuestionariocontestado',
            table='cuestionarioContestado',
        ),
    ]
