# Generated by Django 4.1.2 on 2022-10-24 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoria', '0016_remove_cuestionariocontestado_ruta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='padremadretutor',
            old_name='telefono',
            new_name='telefonotutor',
        ),
    ]
