# Generated by Django 4.1.2 on 2022-10-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoria', '0017_rename_telefono_padremadretutor_telefonotutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionariocontestado',
            name='archivo',
            field=models.FileField(upload_to='Respuestas/Cuestionarios/%Y/%m/%d'),
        ),
    ]
