# Generated by Django 4.1.2 on 2022-10-31 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoria', '0021_alter_cita_fechasolicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
