# Generated by Django 4.1.2 on 2022-10-31 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoria', '0022_alter_cita_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='idEstado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.estado'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='lugar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
