# Generated by Django 4.1.2 on 2022-11-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoria', '0028_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='anoActual',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institucion',
            name='periodoActual',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=3),
            preserve_default=False,
        ),
    ]
