# Generated by Django 4.1.2 on 2022-11-12 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoria', '0030_remove_reportesemestralgrupal_fechalimite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportesemestralgrupal',
            name='idEstado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tutoria.estado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportesemestralgrupal',
            name='idGrupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tutoria.grupo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportesemestralgrupal',
            name='periodo',
            field=models.IntegerField(),
        ),
    ]
