# Generated by Django 4.1.2 on 2022-11-13 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoria', '0031_alter_reportesemestralgrupal_idestado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportesemestralgrupal',
            name='fechaEnvio',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
