# Generated by Django 4.1.2 on 2022-11-13 07:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoria', '0032_reportesemestralgrupal_fechaenvio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportesemestraldepartamento',
            name='fechaLimite',
        ),
        migrations.RemoveField(
            model_name='reportesemestraldepartamento',
            name='ruta',
        ),
        migrations.AddField(
            model_name='reportesemestraldepartamento',
            name='ano',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportesemestraldepartamento',
            name='archivo',
            field=models.FileField(default='', upload_to='CoordinadorTutoriaDepartamentoAcademico/ReporteSemestral'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportesemestraldepartamento',
            name='fechaEnvio',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportesemestraldepartamento',
            name='periodo',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportesemestraldepartamento',
            name='idEstado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tutoria.estado'),
            preserve_default=False,
        ),
    ]
