# Generated by Django 4.1.2 on 2022-11-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoria', '0036_alter_personaltec_correopersonal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.CharField(max_length=8)),
                ('nombres', models.CharField(max_length=35)),
                ('apellidos', models.CharField(max_length=35)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('domicilio', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('semestre', models.IntegerField(max_length=3)),
            ],
        ),
    ]
