# Generated by Django 4.1.2 on 2022-11-20 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoria', '0040_alter_tutorado_correopersonal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteSemestralDepartamentalV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.CharField(blank=True, max_length=200, null=True)),
                ('ano', models.PositiveIntegerField()),
                ('periodo', models.PositiveIntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('actividad1', models.TextField()),
                ('actividad2', models.TextField()),
                ('actividad3', models.TextField()),
                ('actividad4', models.TextField()),
                ('actividad5', models.TextField()),
                ('actividad6', models.TextField()),
                ('actividad7', models.TextField()),
                ('actividad8', models.TextField()),
                ('actividad9', models.TextField()),
                ('actividad10', models.TextField()),
                ('acciones', models.TextField()),
                ('coordinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.personaltec')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.departamentoacademico')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.estado')),
            ],
            options={
                'verbose_name': 'ReporteSemestralDepartamentalV2',
                'verbose_name_plural': 'ReportesSemestralesDepartamentalesV2',
                'db_table': 'reporteSemestralDepartamentalV2',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReporteSemestralGrupalV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.CharField(blank=True, max_length=200, null=True)),
                ('ano', models.PositiveIntegerField()),
                ('periodo', models.PositiveIntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.estado')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.grupo')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.personaltec')),
            ],
            options={
                'verbose_name': 'ReporteSemestralGrupalV2',
                'verbose_name_plural': 'ReportesSemestralesGrupalesV2',
                'db_table': 'reporteSemestralGrupalV2',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TutorReporteSemestralDepartamentalV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutoriaGrupal', models.CharField(max_length=200)),
                ('tutoriaIndividual', models.CharField(max_length=200)),
                ('estudianteCanalizado', models.TextField()),
                ('areaCanalizada', models.TextField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.grupo')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.reportesemestraldepartamentalv2')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.personaltec')),
            ],
            options={
                'verbose_name': 'TutorReporteSemestralDepartamentalV2',
                'verbose_name_plural': 'TutoresReportesSemestralesDepartamentalesV2',
                'db_table': 'tutorReporteSemestralDepartamentalV2',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TutoradoReporteSemestralGrupalV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutoriaGrupal', models.CharField(max_length=200)),
                ('tutoriaIndividual', models.CharField(max_length=200)),
                ('observaciones', models.CharField(choices=[('Excelente', 'Excelente'), ('Notable', 'Notable'), ('Bueno', 'Bueno'), ('Suficiente', 'Suficiente'), ('Insuficiente', 'Insuficiente')], max_length=20)),
                ('estudianteCanalizado', models.TextField()),
                ('asistencia', models.FloatField()),
                ('credito', models.BooleanField(null=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.reportesemestralgrupalv2')),
                ('tutorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.tutorado')),
            ],
            options={
                'verbose_name': 'TutoradoReporteSemestralGrupalV2',
                'verbose_name_plural': 'TutoradosReportesSemestralesGrupalesV2',
                'db_table': 'tutoradoReporteSemestralGrupalV2',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReporteSemestralInstitucionalV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.CharField(blank=True, max_length=200, null=True)),
                ('ano', models.PositiveIntegerField()),
                ('periodo', models.PositiveIntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('coordinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.personaltec')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.estado')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.institucion')),
            ],
            options={
                'verbose_name': 'ReporteSemestralInstitucionalV2',
                'verbose_name_plural': 'ReportesSemestralesInstitucionalesV2',
                'db_table': 'reporteSemestralInstitucionalV2',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PITInstitucionalV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.CharField(blank=True, max_length=200, null=True)),
                ('ano', models.PositiveIntegerField()),
                ('periodo', models.PositiveIntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.estado')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.institucion')),
                ('jefe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.personaltec')),
            ],
            options={
                'verbose_name': 'PITInstitucionalV2',
                'verbose_name_plural': 'PITsInstitucionalesV2',
                'db_table': 'pitInstitucionalV2',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PATDepartamentalV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='CoordinadorTutoriaDepartamentoAcademico/PAT')),
                ('ano', models.PositiveIntegerField()),
                ('periodo', models.PositiveIntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('coordinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.personaltec')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.departamentoacademico')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.estado')),
            ],
            options={
                'verbose_name': 'PATDepartamentalV2',
                'verbose_name_plural': 'PATsDepartamentalesV2',
                'db_table': 'patDepartamentalV2',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoInstitucionalV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='CoordinadorInstitucionalTutoria/Diagnostico')),
                ('ano', models.PositiveIntegerField()),
                ('periodo', models.PositiveIntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('coordinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.personaltec')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.estado')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.institucion')),
            ],
            options={
                'verbose_name': 'DiagnosticoInstitucionalV2',
                'verbose_name_plural': 'DiagnosticosInstitucionalesV2',
                'db_table': 'diagnosticoInstitucionalV2',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ConstanciaTutorV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.CharField(blank=True, max_length=200, null=True)),
                ('ano', models.PositiveIntegerField()),
                ('periodo', models.PositiveIntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.estado')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.grupo')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoria.personaltec')),
            ],
            options={
                'verbose_name': 'ConstanciaTutorV2',
                'verbose_name_plural': 'ConstanciasTutoresV2',
                'db_table': 'constanciaTutorV2',
                'ordering': ['id'],
            },
        ),
    ]
