# Generated by Django 4.1.2 on 2022-11-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoria', '0041_reportesemestraldepartamentalv2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel2',
            name='semestre',
            field=models.IntegerField(),
        ),
    ]
