# Generated by Django 4.1.2 on 2022-11-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoria', '0042_alter_excel2_semestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='registrarAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.CharField(max_length=8)),
                ('nombres', models.CharField(max_length=35)),
                ('apellidos', models.CharField(max_length=35)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('domicilio', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('semestre', models.IntegerField(max_length=3)),
            ],
            options={
                'verbose_name': 'registrarAlumno',
                'verbose_name_plural': 'registrarAlumnos',
                'db_table': 'registrarAlumno',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Excel2',
        ),
        migrations.AddField(
            model_name='credito',
            name='nombre_doc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
