# Generated by Django 4.1.2 on 2022-11-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoria', '0043_registraralumno_delete_excel2_credito_nombre_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registraralumno',
            name='semestre',
            field=models.IntegerField(),
        ),
    ]
