# Generated by Django 4.1.2 on 2022-11-27 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoria', '0044_alter_registraralumno_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='idInstitucion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tutoria.institucion'),
            preserve_default=False,
        ),
    ]
