# Generated by Django 4.1.2 on 2022-11-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoria', '0045_cita_idinstitucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='registrarPersonalTec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.CharField(max_length=8)),
                ('nombres', models.CharField(max_length=35)),
                ('apellidos', models.CharField(max_length=35)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'registrarPersonalTec',
                'verbose_name_plural': 'registrarPersonalTecs',
                'db_table': 'registrarPersonalTec',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='pat',
            name='idDepartamentoAcademico',
        ),
        migrations.RemoveField(
            model_name='pat',
            name='idEstado',
        ),
        migrations.RemoveField(
            model_name='pat',
            name='idPersonalTec',
        ),
        migrations.RemoveField(
            model_name='pit',
            name='idEstado',
        ),
        migrations.RemoveField(
            model_name='pit',
            name='idInstitucion',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='idGrupoRespuesta',
        ),
        migrations.RemoveField(
            model_name='reportesemestraldepartamento',
            name='idDepartamentoAcademico',
        ),
        migrations.RemoveField(
            model_name='reportesemestraldepartamento',
            name='idEstado',
        ),
        migrations.RemoveField(
            model_name='reportesemestraldepartamento',
            name='idPersonalTec',
        ),
        migrations.RemoveField(
            model_name='reportesemestralgrupal',
            name='idEstado',
        ),
        migrations.RemoveField(
            model_name='reportesemestralgrupal',
            name='idGrupo',
        ),
        migrations.RemoveField(
            model_name='reportesemestralgrupal',
            name='idPersonalTec',
        ),
        migrations.RemoveField(
            model_name='reportesemestralinstitucional',
            name='idEstado',
        ),
        migrations.RemoveField(
            model_name='reportesemestralinstitucional',
            name='idInstitucion',
        ),
        migrations.RemoveField(
            model_name='reportesemestralinstitucional',
            name='idPersonalTec',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='idGrupoRespuesta',
        ),
        migrations.RemoveField(
            model_name='respuestacontestada',
            name='idCuestionario',
        ),
        migrations.RemoveField(
            model_name='respuestacontestada',
            name='idPregunta',
        ),
        migrations.RemoveField(
            model_name='respuestacontestada',
            name='idRespuesta',
        ),
        migrations.RemoveField(
            model_name='respuestacontestada',
            name='idTutorado',
        ),
        migrations.RemoveField(
            model_name='registraralumno',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='registraralumno',
            name='telefono',
        ),
        migrations.DeleteModel(
            name='ConstanciaTutor',
        ),
        migrations.DeleteModel(
            name='GrupoRespuesta',
        ),
        migrations.DeleteModel(
            name='PAT',
        ),
        migrations.DeleteModel(
            name='PIT',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.DeleteModel(
            name='ReporteSemestralDepartamento',
        ),
        migrations.DeleteModel(
            name='ReporteSemestralGrupal',
        ),
        migrations.DeleteModel(
            name='ReporteSemestralInstitucional',
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
        migrations.DeleteModel(
            name='RespuestaContestada',
        ),
    ]
