# Generated by Django 4.1.2 on 2022-11-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoria', '0046_fechalimite_remove_pat_iddepartamentoacademico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='registrarPersonalTec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.CharField(max_length=8)),
                ('nombres', models.CharField(max_length=35)),
                ('apellidos', models.CharField(max_length=35)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'registrarPersonalTec',
                'verbose_name_plural': 'registrarPersonalTecs',
                'db_table': 'registrarPersonalTec',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='registraralumno',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='registraralumno',
            name='telefono',
        ),
    ]
