# Generated by Django 4.1.2 on 2022-11-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoria', '0046_registrarpersonaltec_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrarpersonaltec',
            name='control',
        ),
        migrations.AddField(
            model_name='registrarpersonaltec',
            name='username',
            field=models.CharField(default='sgt', max_length=30),
            preserve_default=False,
        ),
    ]
