# Generated by Django 4.1.2 on 2022-11-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoria', '0048_remove_registrarpersonaltec_control_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltec',
            name='correoPersonal',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='personaltec',
            name='domicilio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personaltec',
            name='edificio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personaltec',
            name='telefono',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
